[options]
buildDir = "nea_work"

[deploy]
startCommand = "gunicorn nea_project.wsgi --workers 2 --threads 2 --bind 0.0.0.0:$PORT"

[build]
buildCommand = "pip install -r requirements.txt && python manage.py collectstatic --noinput"
