# Generated by Django 4.2.16 on 2026-03-16 06:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="NEAUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("username", models.CharField(max_length=50, unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("full_name", models.CharField(max_length=150)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("MD", "Managing Director"),
                            ("DMD", "Deputy Managing Director"),
                            ("DIRECTOR", "Director"),
                            ("PROVINCIAL_MANAGER", "Provincial Manager"),
                            ("DC_MANAGER", "DC Manager"),
                            ("DC_STAFF", "DC Staff"),
                        ],
                        default="DC_STAFF",
                        max_length=30,
                    ),
                ),
                ("employee_id", models.CharField(blank=True, max_length=30)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("designation", models.CharField(blank=True, max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                (
                    "date_joined",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("last_login_ip", models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "NEA User",
                "verbose_name_plural": "NEA Users",
            },
        ),
        migrations.CreateModel(
            name="ConsumerCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("code", models.CharField(max_length=20, unique=True)),
                ("display_order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["display_order"],
            },
        ),
        migrations.CreateModel(
            name="DistributionCenter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("code", models.CharField(max_length=30, unique=True)),
                ("address", models.TextField(blank=True)),
                ("contact", models.CharField(blank=True, max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="FiscalYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year_bs", models.CharField(max_length=20, unique=True)),
                ("year_ad_start", models.IntegerField()),
                ("year_ad_end", models.IntegerField()),
                (
                    "loss_target_percent",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-year_ad_start"],
            },
        ),
        migrations.CreateModel(
            name="LossReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted"),
                            ("PROVINCIAL_REVIEWED", "Provincial Reviewed"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="DRAFT",
                        max_length=25,
                    ),
                ),
                (
                    "total_received_kwh",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_utilised_kwh",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_loss_kwh",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "cumulative_loss_percent",
                    models.DecimalField(decimal_places=4, default=0, max_digits=7),
                ),
                ("submission_date", models.DateTimeField(blank=True, null=True)),
                ("review_date", models.DateTimeField(blank=True, null=True)),
                ("approval_date", models.DateTimeField(blank=True, null=True)),
                ("remarks", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "distribution_center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loss_reports",
                        to="nea_loss.distributioncenter",
                    ),
                ),
                (
                    "fiscal_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loss_reports",
                        to="nea_loss.fiscalyear",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submitted_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": [
                    "-fiscal_year__year_ad_start",
                    "distribution_center__name",
                ],
                "unique_together": {("distribution_center", "fiscal_year")},
            },
        ),
        migrations.CreateModel(
            name="MeterPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("code", models.CharField(blank=True, max_length=50)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("SUBSTATION", "Substation"),
                            ("FEEDER_11KV", "11 kV Feeder"),
                            ("FEEDER_33KV", "33 kV Feeder"),
                            ("INTERBRANCH", "Interbranch Import"),
                            ("IPP", "Independent Power Producer"),
                            ("EXPORT_DC", "Export to Other DC"),
                            ("EXPORT_IPP", "Export to IPP"),
                        ],
                        max_length=20,
                    ),
                ),
                ("voltage_level", models.CharField(blank=True, max_length=20)),
                (
                    "multiplying_factor",
                    models.DecimalField(decimal_places=3, default=1, max_digits=10),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "distribution_center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meter_points",
                        to="nea_loss.distributioncenter",
                    ),
                ),
            ],
            options={
                "ordering": ["source_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="Province",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=20, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ProvincialOffice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("code", models.CharField(max_length=30, unique=True)),
                ("address", models.TextField(blank=True)),
                ("contact", models.CharField(blank=True, max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "province",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offices",
                        to="nea_loss.province",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("REPORT_SUBMITTED", "Report Submitted"),
                            ("REPORT_APPROVED", "Report Approved"),
                            ("REPORT_REJECTED", "Report Rejected"),
                            ("LOSS_EXCEEDED", "Loss Target Exceeded"),
                            ("REMINDER", "Submission Reminder"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "related_report",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nea_loss.lossreport",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MonthlyLossData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "month",
                    models.IntegerField(
                        choices=[
                            (1, "Shrawan"),
                            (2, "Bhadra"),
                            (3, "Ashwin"),
                            (4, "Kartik"),
                            (5, "Mangsir"),
                            (6, "Poush"),
                            (7, "Magh"),
                            (8, "Falgun"),
                            (9, "Chaitra"),
                            (10, "Baisakh"),
                            (11, "Jestha"),
                            (12, "Ashadh"),
                        ]
                    ),
                ),
                ("month_name", models.CharField(max_length=20)),
                (
                    "total_energy_import",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_energy_export",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "net_energy_received",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_energy_utilised",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "loss_unit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "monthly_loss_percent",
                    models.DecimalField(decimal_places=4, default=0, max_digits=7),
                ),
                (
                    "cumulative_loss_percent",
                    models.DecimalField(decimal_places=4, default=0, max_digits=7),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monthly_data",
                        to="nea_loss.lossreport",
                    ),
                ),
            ],
            options={
                "ordering": ["month"],
                "unique_together": {("report", "month")},
            },
        ),
        migrations.AddField(
            model_name="distributioncenter",
            name="provincial_office",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="distribution_centers",
                to="nea_loss.provincialoffice",
            ),
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=50)),
                ("model_name", models.CharField(max_length=50)),
                ("object_id", models.IntegerField(null=True)),
                ("description", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddField(
            model_name="neauser",
            name="distribution_center",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="nea_loss.distributioncenter",
            ),
        ),
        migrations.AddField(
            model_name="neauser",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                related_name="user_set",
                related_query_name="user",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
        migrations.AddField(
            model_name="neauser",
            name="provincial_office",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="nea_loss.provincialoffice",
            ),
        ),
        migrations.AddField(
            model_name="neauser",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="user_set",
                related_query_name="user",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
        migrations.CreateModel(
            name="MeterReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "present_reading",
                    models.DecimalField(decimal_places=3, max_digits=15),
                ),
                (
                    "previous_reading",
                    models.DecimalField(decimal_places=3, max_digits=15),
                ),
                (
                    "difference",
                    models.DecimalField(decimal_places=3, default=0, max_digits=15),
                ),
                (
                    "multiplying_factor",
                    models.DecimalField(decimal_places=3, default=1, max_digits=10),
                ),
                (
                    "unit_kwh",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "meter_point",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="readings",
                        to="nea_loss.meterpoint",
                    ),
                ),
                (
                    "monthly_data",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meter_readings",
                        to="nea_loss.monthlylossdata",
                    ),
                ),
            ],
            options={
                "unique_together": {("monthly_data", "meter_point")},
            },
        ),
        migrations.CreateModel(
            name="EnergyUtilisation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "energy_kwh",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("remarks", models.CharField(blank=True, max_length=200)),
                (
                    "consumer_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nea_loss.consumercategory",
                    ),
                ),
                (
                    "monthly_data",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="energy_utilisations",
                        to="nea_loss.monthlylossdata",
                    ),
                ),
            ],
            options={
                "unique_together": {("monthly_data", "consumer_category")},
            },
        ),
        migrations.CreateModel(
            name="ConsumerCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count", models.IntegerField(default=0)),
                ("remarks", models.CharField(blank=True, max_length=200)),
                (
                    "consumer_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nea_loss.consumercategory",
                    ),
                ),
                (
                    "monthly_data",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consumer_counts",
                        to="nea_loss.monthlylossdata",
                    ),
                ),
            ],
            options={
                "unique_together": {("monthly_data", "consumer_category")},
            },
        ),
    ]
