# Generated by Django 4.2.16 on 2026-03-22 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("nea_loss", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="consumercategory",
            options={"ordering": ["display_order", "name"]},
        ),
        migrations.AddField(
            model_name="consumercategory",
            name="distribution_center",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consumer_categories",
                to="nea_loss.distributioncenter",
            ),
        ),
        migrations.AlterField(
            model_name="consumercategory",
            name="code",
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name="consumercategory",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
