# Generated by Django 4.2.17 on 2026-03-24 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nea_loss", "0002_flexible_consumer_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="lossreport",
            name="month",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Shrawan"),
                    (2, "Bhadra"),
                    (3, "Ashwin"),
                    (4, "Kartik"),
                    (5, "Mangsir"),
                    (6, "Poush"),
                    (7, "Magh"),
                    (8, "Falgun"),
                    (9, "Chaitra"),
                    (10, "Baisakh"),
                    (11, "Jestha"),
                    (12, "Ashadh"),
                ],
                default=1,
            ),
        ),
    ]
