# Generated by Django 4.2.17 on 2026-03-24 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nea_loss", "0003_lossreport_month"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lossreport",
            options={
                "ordering": [
                    "-fiscal_year__year_ad_start",
                    "month",
                    "distribution_center__name",
                ]
            },
        ),
        migrations.AlterUniqueTogether(
            name="lossreport",
            unique_together={("distribution_center", "fiscal_year", "month")},
        ),
    ]
