# Generated by Django 4.2.16 on 2026-03-26 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nea_loss', '0004_alter_lossreport_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neauser',
            name='role',
            field=models.CharField(choices=[('SYS_ADMIN', 'System Administrator'), ('MD', 'Managing Director'), ('DMD', 'Deputy Managing Director'), ('DIRECTOR', 'Director'), ('PROVINCIAL_MANAGER', 'Provincial Manager'), ('DC_MANAGER', 'DC Manager'), ('DC_STAFF', 'DC Staff')], default='DC_STAFF', max_length=30),
        ),
        migrations.CreateModel(
            name='ProvincialReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField(choices=[(1, 'Shrawan'), (2, 'Bhadra'), (3, 'Ashwin'), (4, 'Kartik'), (5, 'Mangsir'), (6, 'Poush'), (7, 'Magh'), (8, 'Falgun'), (9, 'Chaitra'), (10, 'Baisakh'), (11, 'Jestha'), (12, 'Ashadh')], default=1)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provincial_reports', to='nea_loss.fiscalyear')),
                ('provincial_office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provincial_reports', to='nea_loss.provincialoffice')),
            ],
            options={
                'ordering': ['-fiscal_year__year_ad_start', 'month'],
                'unique_together': {('provincial_office', 'fiscal_year', 'month')},
            },
        ),
    ]
