# Generated by Django 4.2.16 on 2026-03-29 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("nea_loss", "0005_add_provincial_report_sysadmin_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="MonthlyMeterPointStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "meter_point",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monthly_statuses",
                        to="nea_loss.meterpoint",
                    ),
                ),
                (
                    "monthly_data",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meter_point_statuses",
                        to="nea_loss.monthlylossdata",
                    ),
                ),
            ],
            options={
                "unique_together": {("monthly_data", "meter_point")},
            },
        ),
    ]
