# Generated by Django 4.2.16 on 2026-03-31 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nea_loss', '0006_add_monthly_meter_point_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meterpoint',
            name='source_type',
            field=models.CharField(choices=[('SUBSTATION', 'Substation'), ('FEEDER_11KV', '11 kV Feeder'), ('FEEDER_33KV', '33 kV Feeder'), ('INTERBRANCH', 'Interbranch Import'), ('IPP', 'Independent Power Producer'), ('ENERGY_IMPORT', 'Energy Import'), ('EXPORT_DC', 'Export to Other DC'), ('EXPORT_IPP', 'Export to IPP'), ('ENERGY_EXPORT', 'Energy Export')], max_length=20),
        ),
        migrations.AlterField(
            model_name='meterreading',
            name='previous_reading',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15),
        ),
    ]
