# Generated by Django 4.2.16 on 2026-04-07 04:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nea_loss', '0009_dcstartmonth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributioncenter',
            name='report_start_month',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Shrawan'), (2, 'Bhadra'), (3, 'Ashwin'), (4, 'Kartik'), (5, 'Mangsir'), (6, 'Poush'), (7, 'Magh'), (8, 'Falgun'), (9, 'Chaitra'), (10, 'Baisakh'), (11, 'Jestha'), (12, 'Ashadh')], default=1, help_text='First month this DC is required to submit a report for the fiscal year. Admin sets this — e.g. a DC added mid-year starts from Mangsir (5).'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='nea_loss.message')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DCYearlyTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_loss_percent', models.DecimalField(decimal_places=3, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('distribution_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yearly_targets', to='nea_loss.distributioncenter')),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dc_yearly_targets', to='nea_loss.fiscalyear')),
                ('set_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dc_yearly_targets_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['fiscal_year', 'distribution_center'],
                'unique_together': {('distribution_center', 'fiscal_year')},
            },
        ),
    ]
